<?php
use PHPUnit\Framework\TestCase;
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 02/01/2020
 * Time: 22:12
 */
class SampleTest extends TestCase
{

    public static function assertTrue($condition, string $message = ''): void
        {
            parent::assertTrue(true, 'Do it again'); // TODO: Change the autogenerated stub
        }


}